### PR TITLE
Pipeline phase 1.1 update eslint config

### PR DESCRIPTION
**Pull request by ejewik**
This PR updates settings in the eslint config file. There
were some options generated by eslint --init when run locally,
like if we are using javascript modules, that I added to the config file.
    
Additionally, I extended AirBnB's style guide instead of the eslint
recommended rules to see if this works for our team. Something to
note is that when setting this up, I updated eslint locally and
installed airbnb related dependencies.
    
I also edited the pre-commit hook for eslint to ignore node_modules.

### CODE REVIEW

**Comment by ejewik** [comment]
@rahuldadlani03 @zainnk902 @dcullenUCSD I added some settings in the config file and extended AirBnB rules. From a little research it seems like it's the most popular style guide for javascript overall, and we can modify the rules as we see fit if some of them get too annoying. Let me know though if you'd rather use a different style guide - it would be easier to change now than later since I installed some dependencies. Don't merge this PR yet if we want to use a different one straight off the bat. 

In the run 'Test Github action with airBnB rules' you can see the results of the linting action there. Minor problems like indentation can actually be auto-fixed through the the command palette in VSCode when the ESLint extension is installed, and are a result of extending the airBnB rules. 

Since using a style guide picks up on things like indentation, we may want to forego formatting for now and work on different parts of the cipipeline. I just noticed that phase 2 is due by the 25th from the canvas assignment writeup, though the assignment's not even out yet.

**Comment by rahuldadlani03** [comment]
Sticking with airBnB rules sounds good to me, if it's already in place and the annoying rules can be automated away via prettier or the eslint extension in VSCode then we should run with them for the sake of time.

Just curious, what other aspects of the pipeline do we need to focus on? Do you mean setting up e2e testing (which we just got a lab for) and implementing a system for only running a subset of unit tests when pushing to a feature branch vs running all unit tests when pushing to development/main?

I think everything looks solid with his PR, good work fixing the warnings and implementing the style rules. I'll let @dcullenUCSD or @zainnk902 have the final word on approval so they can weigh in.

**Comment by ejewik** [comment]
@rahuldadlani03 Thank you for reviewing this so quickly and also for creating the doc on github actions. That was super helpful! 

About the other aspects of the pipeline we need to focus on, I may have misread the assignment. I assumed that checkpoint 2 (due on the 25th) corresponded to phase 2, and got confused when I realized that there was no assignment writeup for phase 2 yet. It's a little odd to me because there are supposed to be three phases - if checkpoint 2 corresponds to phase 1, I don't know how much time they're going to give us for subsequent phases since it's already week 8. I asked Sasya earlier about phase 2, so hopefully we'll get a response on that soon. 

For now, it may be a good idea to prioritize merging into pipeline-phase-1 and then to main once Dylan's finished with the action for JSDocs and Zain's finished with changing yarn to npm for jest, so that the developers don't get too far along without writing tests or checking for style. If Zain or Dylan have tasks on the dev team and need to focus on that/are blocked with assignments right now, I can take their tasks so that we can merge that faster. We should also set up the branches soon so that the dev team has develop to work off of. 

Some of the things they mentioned in the assignment writeup that we may have to implement in future phases are: code coverage reporting, packaging, deployment, and minification quoted from the writeup. Since they'll probably get more specific when the new assignment writeups are released it's probably best to hold off on this for now.

**Comment by rahuldadlani03** [comment]
Everything looks good!

**Review by rahuldadlani03 — APPROVED** [review]
Everything looks good

**Pull request merged**
