### PR TITLE
Pipeline phase 1.1 jsdocs

### PR DESCRIPTION
**Pull request by ejewik**
This PR uses an existing action to run JSDocs and deploy to Github Pages on the gh-pages branch. Since actions run workflows in a virtual machine, we can't just run JSDocs alone. The deploy step commits the generated documentation created from JSDoc comments to the remote gh-pages branch which is then deployed to the link https://cse110-sp21-group15.github.io/cse110-sp21-group15/. This automatically generates documentation in the form of HTML files for any method/object that has JSDoc style comments.

Something to note is that in order to deploy to pages I had to generate an SSH deploy key and allow write access to it, so that the jsdocs action can commit directly to the remote gh-pages branch.  I also added the private key as ACTIONS_DEPLOY_KEY under Secrets. The steps I followed are listed under Tips and FAQ's in the link below.

Link for adding an SSH deploy key: https://github.com/peaceiris/actions-gh-pages (under Tips and FAQ's)
Link to the actions used to run and deploy: https://github.com/marketplace/actions/jsdoc-action

### CODE REVIEW

**Comment by ejewik** [comment]
@rahuldadlani03 @zainnk902 I created a PR for the JSDocs action. If both of you could review it that would be great. Thanks!

**Comment by rahuldadlani03** [comment]
@ejewik Solid work! It's pretty cool that our docs are automatically generated and deployed. There's an issue with having our docs hosted on Pages though.

I was planning to use our GitHub Pages to host the JRNL landing page. Since we only have one domain, we would have to setup a different server to host the website if we let the docs live here.

@ejewik @zainnk902 Let's have a meeting to discuss what our options are before we approve this PR

**Review by rahuldadlani03 — APPROVED** [review]
The code looks good!

**Review by zainnk902 — COMMENTED** [review]
lgtm!

**Pull request merged**
